server:
  port: 8030
spring:
  application:
    name: client
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html     #后缀
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    inttance:
      perfer-ip-address: true